### ISSUE TITLE
throw new Exception Error

### ISSUE THREAD

**Issue by zanettin** [Tealium/integration-angularjs#10]
Hi

I get a "ReferenceError: Exception is not defined" error here https://github.com/Tealium/integration-angularjs/blob/master/tealium.js#L21

Referring to this doc, new Exception is no default Error Type in JS:
http://www.javascriptkit.com/javatutors/trycatch2.shtml

I've change to local copy to "throw ('please configure Tealium first');"

**Comment by tygavin** [comment]
Using `new Error("message")` now, thanks again..
