### ISSUE TITLE
npm support please

### ISSUE THREAD

**Issue by theDustRoom** [Tealium/integration-angularjs#18]
I see that you have included support for bower but as many developers are moving away from using it (as it's unnecessary and basically redundant) including this within the _npm_ registry would be beneficial.

See this old post: https://gofore.com/stop-using-bower/

Even if you just include a compatible _package.json_ without submitting to _npm_ we could install via git url.

**Comment by tygavin** [comment]
Agreed, we need package.json as well.  Feel free to submit a pull request if you'd like.

**Comment by tygavin** [comment]
Thanks again @theDustRoom for the package.json update.. and for the article on bower.
