### ISSUE TITLE
Expose setViewIdMap

### ISSUE THREAD

**Issue by theDustRoom** [Tealium/integration-angularjs#19]
Can you expose the _setViewIdMap_ method so this can be configured/updated from within a service?

It's not ideal to have to include lots of analytics within the main application config method and reduces scaleability.

**Comment by tygavin** [comment]
This is now updated.  Let me know if this is what you were looking for. 

https://github.com/Tealium/integration-angularjs/pull/22

I've also added support for a new function "addViewIdMapEntry"

```
tealium.addViewIdMapEntry( "/template2.html", function() {
          var data = {
            "page_type" : "product",
            "key2"  : "value2"
          };
          return data;
        });
```

**Comment by tygavin** [comment]
I'll close the issue and re-open if needed.
