### ISSUE TITLE
Script cs.js added on each "view" event

### ISSUE THREAD

**Issue by ggsurrel** [Tealium/integration-angularjs#28]
I noticed that each time I generate a view event, a new line is added in the header of my webpage : 
```html
<script type="text/javascript" async="" id="tealium-tag-3005" src="https://sb.scorecardresearch.com/c2/5641052/cs.js"></script>
```

So, after some time browsing the site, the header is filled up with hundreds of lines like that.

I found that this line is added by this function (in utag.8.js): 
```js
(function() {
  var id = "tealium-tag-3005";
  if (a === "link" && document.getElementById(id)) {
    return;
  }
  var t = document.createElement("script");
  t.type = "text/javascript";
  t.async = true;
  t.id = id;
  t.src = u.data.base_url;
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(t, s);
})();
```
So, in case of a "link" event, the script addition is avoided when already present, but for a "view" event, the script is added every time.

**Comment by tygavin** [comment]
This appears to be related to a specific tag (comScore) and is not related to this integration.  Please contact your Account Manager for instructions on how to use the latest Tag template for comScore.

**Comment by adamwolfers** [comment]
Also, there's a comment in our comScore tag template that says "for utag.view calls, the cs.js should be reloaded (per ComScore)".  I don't know if this is still a requirement.
