### ISSUE TITLE
View call at run method

### ISSUE THREAD

**Issue by anbuneeda** [Tealium/integration-angularjs#7]
If i try to fire a view call at run method, though utag.js file is loaded , utag is returning undefined. Seems like utag.js will load and connect to utag_data only after angular loads. do u have any sample to call in angular run method

**Comment by tygavin** [comment]
There is a potential timing issue if you call tealium.view() function while utag.js is in process of downloading/loading.  The tealium.view event will not be tracked.  I'll update shortly with a fix.

**Comment by tygavin** [comment]
@anbuneeda Let me know if the recent updates resolve this issue.  I've also update the contents in the /sample folder.

**Comment by anbuneeda** [comment]
@tygavin thanks for your response. I will check this out. I sorted out in a different way but the approach is somewhat similar.

1.create an array and store the data.
2.Introduced a callback after uatag load.
3. In the callback loop through the array and send the utag view call.

(function(a, b, c, d) {
a = '//tags.tiqcdn.com/utag/'
		+ config.path + '/utag.js';
b = document;
c = 'script';
d = b.createElement(c);
d.src = a;
d.type = 'text/java' + c;
d.async = true;
a = b.getElementsByTagName(c)[0];
a.parentNode.insertBefore(d, a);

d.onload = function() { // for modern
						// browsers
	if (!d.onloadDone) {
		d.onloadDone = true;
		sendDelayedCalls();
		
	}
};
// uses onreadystatechange, for IE9
d.onreadystatechange = function() {
	if (("loaded" === d.readyState || "complete" === d.readyState)
			&& !d.onloadDone) {
		d.onloadDone = true;
		sendDelayedCalls();
		
	}
}
//////////////////////////////////////////////////
var sendDelayedCalls = function() {
if (!window.utag)
	return;
if (delayViews.length <= 0)
	return;

// delayViews.sort();
while (delayViews.length > 0) {
	delayView = (delayViews.shift()[1]);
	utag.view(delayView);
}
};
///////////////////////////

var view = function(data) {
if (window.utag)
	window.utag.view(data);
else
	storeDelayedCalls(data);
};

**Comment by tygavin** [comment]
@anbuneeda Thanks for sharing your code as well.  I'll mark this as resolved.
