### ISSUE TITLE
Tealium fails in Strict DI Mode

### ISSUE THREAD

**Issue by theDustRoom** [Tealium/integration-angularjs#9]
When running the AngularJS in production, the tealium integration fails in Strict DI Mode.

See: https://code.angularjs.org/1.5.5/docs/guide/production

**Comment by tygavin** [comment]
@theDustRoom Thanks for pointing this out..  This AngularJS rookie just learned something new.  Let me know if recent updates look good.  I've also added the following the sample index.html file.

`<body ng-app="App" ng-strict-di>`
